[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"
rustflags = ["-C", "link-args=-fuse-ld=lld"]

# 如果是 ARM64 Linux 目標
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
rustflags = ["-C", "link-args=-fuse-ld=lld"]